In [5]:
!pip install xlrd
import pandas as pd

Defaulting to user installation because normal site-packages is not writeable
Collecting xlrd
  Downloading xlrd-2.0.2-py2.py3-none-any.whl.metadata (3.5 kB)
Downloading xlrd-2.0.2-py2.py3-none-any.whl (96 kB)
Installing collected packages: xlrd
Successfully installed xlrd-2.0.2

In [13]:
import pandas as pd

df = pd.read_csv(
    r"C:\Users\Kalpesh\AppData\Local\Packages\5319275A.WhatsAppDesktop_cv1g1gvanyjgm\LocalState\sessions\159FB47D636CFA37C6A02C10C88D59233D4A0F13\transfers\2026-39\dataset_Facebook.xls",sep=";"
)

df.head()

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393

In [14]:
df.shape

(500, 19)

In [15]:
df.columns

Index(['Page total likes', 'Type', 'Category', 'Post Month', 'Post Weekday',
       'Post Hour', 'Paid', 'Lifetime Post Total Reach',
       'Lifetime Post Total Impressions', 'Lifetime Engaged Users',
       'Lifetime Post Consumers', 'Lifetime Post Consumptions',
       'Lifetime Post Impressions by people who have liked your Page',
       'Lifetime Post reach by people who like your Page',
       'Lifetime People who have liked your Page and engaged with your post',
       'comment', 'like', 'share', 'Total Interactions'],
      dtype='str')

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 19 columns):
 #   Column                                                               Non-Null Count  Dtype
---  ------                                                               --------------  -----
 0   Page total likes                                                     500 non-null    int64
 1   Type                                                                 500 non-null    str
 2   Category                                                             500 non-null    int64
 3   Post Month                                                           500 non-null    int64
 4   Post Weekday                                                         500 non-null    int64
 5   Post Hour                                                            500 non-null    int64
 6   Paid                                                                 499 non-null    float64
 7   Lifetime Post Total Reach                                            500 non-null    int64
 8   Lifetime Post Total Impressions                                      500 non-null    int64
 9   Lifetime Engaged Users                                               500 non-null    int64
 10  Lifetime Post Consumers                                              500 non-null    int64
 11  Lifetime Post Consumptions                                           500 non-null    int64
 12  Lifetime Post Impressions by people who have liked your Page         500 non-null    int64
 13  Lifetime Post reach by people who like your Page                     500 non-null    int64
 14  Lifetime People who have liked your Page and engaged with your post  500 non-null    int64
 15  comment                                                              500 non-null    int64
 16  like                                                                 499 non-null    float64
 17  share                                                                496 non-null    float64
 18  Total Interactions                                                   500 non-null    int64
dtypes: float64(3), int64(15), str(1)
memory usage: 74.3 KB

In [17]:
df.describe()

,Page total likes,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
count,500.000000,500.000000,500.000000,500.000000,500.000000,499.000000,500.00000,5.000000e+02,500.000000,500.000000,500.000000,5.000000e+02,500.000000,500.000000,500.00000,499.000000,496.000000,500.000000
mean,123194.176000,1.880000,7.038000,4.150000,7.840000,0.278557,13903.36000,2.958595e+04,920.344000,798.772000,1415.130000,1.676638e+04,6585.488000,609.986000,7.48200,177.945892,27.266129,212.120000
std,16272.813214,0.852675,3.307936,2.030701,4.368589,0.448739,22740.78789,7.680325e+04,985.016636,882.505013,2000.594118,5.979102e+04,7682.009405,612.725618,21.18091,323.398742,42.613292,380.233118
min,81370.000000,1.000000,1.000000,1.000000,1.000000,0.000000,238.00000,5.700000e+02,9.000000,9.000000,9.000000,5.670000e+02,236.000000,9.000000,0.00000,0.000000,0.000000,0.000000
25%,112676.000000,1.000000,4.000000,2.000000,3.000000,0.000000,3315.00000,5.694750e+03,393.750000,332.500000,509.250000,3.969750e+03,2181.500000,291.000000,1.00000,56.500000,10.000000,71.000000
50%,129600.000000,2.000000,7.000000,4.000000,9.000000,0.000000,5281.00000,9.051000e+03,625.500000,551.500000,851.000000,6.255500e+03,3417.000000,412.000000,3.00000,101.000000,19.000000,123.500000
75%,136393.000000,3.000000,10.000000,6.000000,11.000000,1.000000,13168.00000,2.208550e+04,1062.000000,955.500000,1463.000000,1.486050e+04,7989.000000,656.250000,7.00000,187.500000,32.250000,228.500000
max,139441.000000,3.000000,12.000000,7.000000,23.000000,1.000000,180480.00000,1.110282e+06,11452.000000,11328.000000,19779.000000,1.107833e+06,51456.000000,4376.000000,372.00000,5172.000000,790.000000,6334.000000

In [18]:
df.dtypes

Page total likes                                                         int64
Type                                                                       str
Category                                                                 int64
Post Month                                                               int64
Post Weekday                                                             int64
Post Hour                                                                int64
Paid                                                                   float64
Lifetime Post Total Reach                                                int64
Lifetime Post Total Impressions                                          int64
Lifetime Engaged Users                                                   int64
Lifetime Post Consumers                                                  int64
Lifetime Post Consumptions                                               int64
Lifetime Post Impressions by people who have liked your Page             int64
Lifetime Post reach by people who like your Page                         int64
Lifetime People who have liked your Page and engaged with your post      int64
comment                                                                  int64
like                                                                   float64
share                                                                  float64
Total Interactions                                                       int64
dtype: object

In [19]:
df.index

RangeIndex(start=0, stop=500, step=1)

In [20]:
df.mean(numeric_only=True)

Page total likes                                                       123194.176000
Category                                                                    1.880000
Post Month                                                                  7.038000
Post Weekday                                                                4.150000
Post Hour                                                                   7.840000
Paid                                                                        0.278557
Lifetime Post Total Reach                                               13903.360000
Lifetime Post Total Impressions                                         29585.948000
Lifetime Engaged Users                                                    920.344000
Lifetime Post Consumers                                                   798.772000
Lifetime Post Consumptions                                               1415.130000
Lifetime Post Impressions by people who have liked your Page            16766.376000
Lifetime Post reach by people who like your Page                         6585.488000
Lifetime People who have liked your Page and engaged with your post       609.986000
comment                                                                     7.482000
like                                                                      177.945892
share                                                                      27.266129
Total Interactions                                                        212.120000
dtype: float64

In [21]:
df.min(numeric_only=True)

Page total likes                                                       81370.0
Category                                                                   1.0
Post Month                                                                 1.0
Post Weekday                                                               1.0
Post Hour                                                                  1.0
Paid                                                                       0.0
Lifetime Post Total Reach                                                238.0
Lifetime Post Total Impressions                                          570.0
Lifetime Engaged Users                                                     9.0
Lifetime Post Consumers                                                    9.0
Lifetime Post Consumptions                                                 9.0
Lifetime Post Impressions by people who have liked your Page             567.0
Lifetime Post reach by people who like your Page                         236.0
Lifetime People who have liked your Page and engaged with your post        9.0
comment                                                                    0.0
like                                                                       0.0
share                                                                      0.0
Total Interactions                                                         0.0
dtype: float64

In [22]:
df.max(numeric_only=True)

Page total likes                                                        139441.0
Category                                                                     3.0
Post Month                                                                  12.0
Post Weekday                                                                 7.0
Post Hour                                                                   23.0
Paid                                                                         1.0
Lifetime Post Total Reach                                               180480.0
Lifetime Post Total Impressions                                        1110282.0
Lifetime Engaged Users                                                   11452.0
Lifetime Post Consumers                                                  11328.0
Lifetime Post Consumptions                                               19779.0
Lifetime Post Impressions by people who have liked your Page           1107833.0
Lifetime Post reach by people who like your Page                         51456.0
Lifetime People who have liked your Page and engaged with your post       4376.0
comment                                                                    372.0
like                                                                      5172.0
share                                                                      790.0
Total Interactions                                                        6334.0
dtype: float64

In [23]:
df.iloc[0]

Page total likes                                                       139441
Type                                                                    Photo
Category                                                                    2
Post Month                                                                 12
Post Weekday                                                                4
Post Hour                                                                   3
Paid                                                                      0.0
Lifetime Post Total Reach                                                2752
Lifetime Post Total Impressions                                          5091
Lifetime Engaged Users                                                    178
Lifetime Post Consumers                                                   109
Lifetime Post Consumptions                                                159
Lifetime Post Impressions by people who have liked your Page             3078
Lifetime Post reach by people who like your Page                         1640
Lifetime People who have liked your Page and engaged with your post       119
comment                                                                     4
like                                                                     79.0
share                                                                    17.0
Total Interactions                                                        100
Name: 0, dtype: object

In [26]:
df.iloc[0:5]

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393

In [31]:
df.iloc[1, 4]

np.int64(3)

In [33]:
df.loc[1, "Type"]

'Status'

In [34]:
df.isnull().sum()

Page total likes                                                       0
Type                                                                   0
Category                                                               0
Post Month                                                             0
Post Weekday                                                           0
Post Hour                                                              0
Paid                                                                   1
Lifetime Post Total Reach                                              0
Lifetime Post Total Impressions                                        0
Lifetime Engaged Users                                                 0
Lifetime Post Consumers                                                0
Lifetime Post Consumptions                                             0
Lifetime Post Impressions by people who have liked your Page           0
Lifetime Post reach by people who like your Page                       0
Lifetime People who have liked your Page and engaged with your post    0
comment                                                                0
like                                                                   1
share                                                                  4
Total Interactions                                                     0
dtype: int64

In [38]:
df["New_Column"] = 100
df

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions,New_Column
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164,100
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80,100
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777,100
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393,100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,85093,Photo,3,1,7,2,0.0,4684,7536,733,708,985,4750,2876,392,5,53.0,26.0,84,100
496,81370,Photo,2,1,5,8,0.0,3480,6229,537,508,687,3961,2104,301,0,53.0,22.0,75,100
497,81370,Photo,1,1,5,2,0.0,3778,7216,625,572,795,4742,2388,363,4,93.0,18.0,115,100
498,81370,Photo,3,1,4,11,0.0,4156,7564,626,574,832,4534,2452,370,7,91.0,38.0,136,100
499,81370,Photo,2,1,4,4,NaN,4188,7292,564,524,743,3861,2200,316,0,91.0,28.0,119,100

In [ ]:
df.drop(["New_Column"], axis=1, inplace=True)
df

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,85093,Photo,3,1,7,2,0.0,4684,7536,733,708,985,4750,2876,392,5,53.0,26.0,84
496,81370,Photo,2,1,5,8,0.0,3480,6229,537,508,687,3961,2104,301,0,53.0,22.0,75
497,81370,Photo,1,1,5,2,0.0,3778,7216,625,572,795,4742,2388,363,4,93.0,18.0,115
498,81370,Photo,3,1,4,11,0.0,4156,7564,626,574,832,4534,2452,370,7,91.0,38.0,136
499,81370,Photo,2,1,4,4,NaN,4188,7292,564,524,743,3861,2200,316,0,91.0,28.0,119